version: "3.3"
services:

  # message queue container
  queue:
    image: rabbitmq:3-management-alpine
    container_name: vocolab_queue
    logging:
      driver: none
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: vocolab
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_DEFAULT_VHOST: vocolab

  # API container
  api:
    restart: unless-stopped
    stop_grace_period: 30s
    image: "voco-api:latest"
    container_name: vocolab_api
    depends_on:
      - queue
    build:
      context: .
      dockerfile: containers/api.Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - containers/dockerconfig/docker.env
    environment:
      # DOCKER PATH ENV
      VC_GUNICORN_WORKERS: 4
      VC_API_BASE_URL: "https://api.vocolab.com"
      VC_version: "v0.5"
      VC_maintainers: "CoML Team, INRIA, ENS, EHESS, CNRS"
      VC_admin_email: "contact@zerospeech.com"
      VC_MAIL_USERNAME: "noreply@vocolab.com"
      VC_MAIL_PASSWORD: "XXXXXXX"
      VC_MAIL_FROM: "noreply@vocolab.com"
      VC_MAIL_FROM_NAME: "Vocolab Challenges"
      VC_MAIL_PORT: 25
      VC_MAIL_SERVER: "mail.vocolab.com"
      VC_MAIL_TLS: "True"
      VC_MAIL_SSL: "False"
    volumes:
      - app-data:/app-data

  # Evaluation worker
  eval_worker:
    restart: unless-stopped
    stop_grace_period: 180s
    image: "voco-worker:latest"
    container_name: vocolab_eval_worker
    command:
      # worker type
      - "worker"
      # log-level
      - '--loglevel=INFO'
      # process pool type
      - "--pool=prefork"
      # number of concurrent processes
      - "--concurrency=2"
      # name of queue
      - "-Q"
      - "eval-queue"
    depends_on:
      - queue
    build:
      context: .
      dockerfile: containers/worker.Dockerfile
    env_file:
      - containers/dockerconfig/docker.env
    environment:
      VC_API_BASE_URL: "https://api.vocolab.com"
      VC_RPC_USERNAME: "vocolab"
      VC_RPC_PASSWORD: "admin"
      VC_RPC_HOST: "vocolab_queue"
    volumes:
      - app-data:/app-data

  # Evaluation worker
  update_worker:
    restart: unless-stopped
    stop_grace_period: 180s
    image: "voco-worker:latest"
    container_name: vocolab_update_worker
    command:
      # worker type
      - "worker"
      # log-level
      - '--loglevel=INFO'
      # process pool type
      - "--pool=prefork"
      # number of concurrent processes
      - "--concurrency=2"
      # name of queue
      - "-Q"
      - "update-queue"
    depends_on:
      - queue
    build:
      context: .
      dockerfile: containers/worker.Dockerfile
    env_file:
      - containers/dockerconfig/docker.env
    environment:
      VC_API_BASE_URL: "https://api.vocolab.com"
      VC_RPC_USERNAME: "vocolab"
      VC_RPC_PASSWORD: "admin"
      VC_RPC_HOST: "vocolab_queue"
    volumes:
      - app-data:/app-data

volumes:
  app-data: