version: "3.3"
services:
  api:
    restart: unless-stopped
    stop_grace_period: 10s
    image: "api:latest"
    container_name: zerospeech_api
    depends_on:
      - queue
    build:
      context: .
      dockerfile: app.Dockerfile
    env_file:
#      - .env
      - test.env
#      - prod.env
    environment:
      # DOCKER PATH ENV
      ZR_STATIC_DIR: /app-data/_static
      ZR_HTML_TEMPLATE_DIR: /templates/pages
      ZR_MATTERMOST_TEMPLATE_DIR: /templates/mattermost
      ZR_DB_HOME: /app-data/db
      # Server Values
      MODULE_NAME: zerospeech.api
      WORKERS_PER_CORE: 1
      MAX_WORKERS: 32
      WEB_CONCURRENCY: 2
      LOG_LEVEL: debug
    volumes:
      - app-data:/app-data
    command: sleep infinity

  queue:
    image: rabbitmq:3-management-alpine
    container_name: zerospeech_queue
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123


  dispatch:
    restart: unless-stopped
    stop_grace_period: 10s
    image: "dispatch:latest"
    container_name: zerospeech_dispatch
    depends_on:
      - queue
    build:
      context: .
      dockerfile: dispatch.Dockerfile
    env_file:
      - test.env
#    environment:
#      # DOCKER PATH ENV
    volumes:
      - app-data:/app-data
    command: sleep infinity


volumes:
  app-data:
