version: "3.3"
services:

  # message queue container
  queue:
    image: rabbitmq:3-management-alpine
    container_name: vocolab_queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123

  # API container
  api:
    restart: unless-stopped
    stop_grace_period: 30s
    image: "voco-api:latest"
    container_name: vocolab_api
    depends_on:
      - queue
    build:
      context: .
      dockerfile: containers/api.Dockerfile
    env_file:
      - containers/dockerconfig/docker.env
    environment:
      # DOCKER PATH ENV
      VC_API_BASE_URL: "https://api.zerospeech.com"
    volumes:
      - app-data:/app-data

  # Evaluation worker
  eval_worker:
    restart: unless-stopped
    stop_grace_period: 180s
    image: "voco-worker:latest"
    container_name: vocolab_evaluation_worker
    depends_on:
      - queue
    build:
      context: .
      dockerfile: containers/worker.Dockerfile
    env_file:
      - containers/dockerconfig/docker.env
    environment:
      ZR_API_BASE_URL: "https://api.zerospeech.com"
    volumes:
      - app-data:/app-data

  # Evaluation worker
  update_worker:
    restart: unless-stopped
    stop_grace_period: 180s
    image: "voco-worker:latest"
    container_name: vocolab_update_worker
    depends_on:
      - queue
    build:
      context: .
      dockerfile: containers/update-worker.Dockerfile
    env_file:
      - containers/dockerconfig/docker.env
    environment:
      ZR_API_BASE_URL: "https://api.zerospeech.com"
    volumes:
      - app-data:/app-data

volumes:
  app-data: